###
GET http://localhost/api/clients
Authorization: Bearer 3|Vgdfh97iU1MdsElhI9OuP31PyMaYhCUvL5o2CDCQ

###
GET http://localhost/api/products/2
Authorization: Bearer 3|Vgdfh97iU1MdsElhI9OuP31PyMaYhCUvL5o2CDCQ

###
DELETE http://localhost/api/token/all
Authorization: Bearer 3|Vgdfh97iU1MdsElhI9OuP31PyMaYhCUvL5o2CDCQ
